- hosts: contoller
  become: yes
  gather_facts: yes
  vars_files:
    - /home/adam/Desktop/DEVSTACK/vars.yml
  roles:
#     - op.keystone_test
#     - op.Glance
#     - op.Glance_test
#      - op.Nova
#      - op.Neutron
#      - op.Horizon
#      - op.firstinstance
       - op.personal
