---
# tasks file for ESX_Boot

- name: Gather vmware host facts
  vmware_host_facts:
    hostname: '{{ vcenter_hostname }}'
    username: '{{ vcenter_username }}'
    password: '{{ vcenter_password }}'
    validate_certs: no
  register: host_facts
- debug : msg="{{ host_facts }}"
