---
# tasks file for op.etcd
- name : install openstack Etcd packages
  yum :
    name: "{{packages}}"
    state: latest

- name : Copy Etcd On Master server
  template:
    src: etcd.j2
    dest: /etc/etcd/etcd.conf
  register: etcdmsg
- debug: msg="{{ etcdmsg }}"

- name : Etcd Restart services
  systemd:
    state: restarted
    name: "{{services}}"
    enabled: yes
    masked: no
