---
# tasks file for op.Memcached
- name : install openstack Memcached packages
  yum :
    name: "{{packages}}"
    state: latest

- name : Copy memcached On Master server
  template:
    src: memcached.j2
    dest: /etc/sysconfig/memcached
  register: memcachedmsg
- debug: msg="{{ memcachedmsg }}"

- name : Memcached Restart services
  systemd:
    state: restarted
    name: "{{services}}"
    enabled: yes
    masked: no
