---
# tasks file for esx.changeRam

- name: Rename a virtual machine (requires the virtual machine's uuid)
  vmware_guest:
    hostname: "{{ vcenter_hostname }}"
    username: "{{ vcenter_username }}"
    password: "{{ vcenter_password }}"
    validate_certs: no
    uuid: "{{ vm_uuid }}"
    name: "{{ vm_name }}"
    state: present
    hardware:
      memory_mb: "{{ mem_choice }}"
      num_cpus: "{{ num_cpus }}"
  delegate_to: localhost
