---
# tasks file for op.personal
#
# - name: Gather facts about previously created networks
#   os_networks_facts:
#
# - name: Gather facts about previously created networks
#   os_server_facts:
#
# - name: Show openstack networks
#   debug:
#     var: openstack_networks
#
# - name: Show openstack networks
#   debug:
#     var: openstack_servers
